name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright HTML Report
      if: always() # Ensures this runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v5.0.0
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=gauravarghodepersonal
          -Dsonar.projectKey=GauravArghodePersonal_last
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate Check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Show Quality Gate Status
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"

    - name: Verify Playwright Report Exists
      if: always()
      run: |
        if [ ! -d "playwright-report" ]; then
        echo "::error::Playwright report directory not found!"
        mkdir -p playwright-report
        echo "<html><body><h1>No test report generated</h1></body></html>" > playwright-report/index.html
        fi

    - name: Deploy HTML Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        destination_dir: ./  # Deploy to root of gh-pages branch
        keep_files: false   # Clean the branch before deploy
        force_orphan: true  # Use a single commit in gh-pages branch
